export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const WORD_REPOSITORY = Symbol('WORD_REPOSITORY');
export const USER_HISTORY_REPOSITORY = Symbol('USER_HISTORY_REPOSITORY');
export const USER_FAVORITE_REPOSITORY = Symbol('USER_FAVORITE_REPOSITORY');
